categoryの生成
CodeGateCircle/communication_app_back pull request #17
Opened 2023-05-03 08:13 UTC by liverHawk

categoryの名前、workspaceのidの入力によってcategoryが一つ生成される。
category:room=1:more
workspace:category=1:more より

belong_to: workspace, has_many:room

また、入力に対する出力がちゃんと正しいものかを判断するテストコードについては、既に実行し成功を確認しています、

2023-05-03 12:13 UTC, yamato-1205 commented on db/migrate/20230503063301_add_workspace_id_column.rb
> +    add_column :categories, :workspace_id, :integer
これ外部キー指定してほしい
modelの方で定義してくれてるから必須ではないと思うけど

2023-05-03 12:26 UTC, liverHawk commented on app/controllers/category_controller.rb
> +      category.save!
なるほど。了解です。

2023-05-03 12:28 UTC, liverHawk commented on app/models/category.rb
> +  end
フロントで厄介ごとですか、、、
修正がてら、すこし調べてみます。

2023-05-03 12:31 UTC, liverHawk commented on db/migrate/20230503063301_add_workspace_id_column.rb
> +    add_column :categories, :workspace_id, :integer
確か、foreign keyみたいなものですよね。
調べて修正します。

2023-05-03 13:16 UTC, liverHawk commented on db/migrate/20230503063301_add_workspace_id_column.rb
> +    add_column :categories, :workspace_id, :integer
ここにadd_foreign_keyを入れました。

2023-05-04 03:56 UTC, yuzuki-aritomo requested changes
確認お願いします！

2023-05-04 03:56 UTC, yuzuki-aritomo commented on app/controllers/category_controller.rb
> +    Category.transaction do
ここの `transaction` は必要ないと思う！
複数回DBにアクセスする場合のみ `transaction`でくくる！

2023-05-04 03:56 UTC, yuzuki-aritomo commented on app/controllers/category_controller.rb
> +                                  })
`params[:workspace_id]`で取得したidが `current_user`に変更権限があるかをチェクしてほしい！
この場合だと本来変更権限がない所属していない `workspace`の `category`も作成出来てしまう

2023-05-04 03:56 UTC, yuzuki-aritomo commented on app/models/category.rb
> +  belongs_to :workspace, dependent: :destroy
`dependent: :destroy`を設定すると categoryを削除した場合に`workspace`まで削除されてしまいます、、

https://qiita.com/eitches/items/1ad419dc705f807735e0

2023-05-04 03:56 UTC, yuzuki-aritomo commented on db/migrate/20230503063301_add_workspace_id_column.rb
> +    add_column :categories, :workspace_id, :integer
`add_reference :categories, :workspace, foreign_key: true`
とういのもある。多分外部キー設定がまだうまくいってなさそう。
修正したら`rails db:migrate:reset`コマンドも実行してみて欲しい。
migrationをやり直してくれる。
https://qiita.com/kurawo___D/items/e3694f7a870a1cc4738e

2023-05-04 03:56 UTC, yuzuki-aritomo commented on docs/openapi.yml
> +  /workspaces/{workspace_id}/update:
あれ、、この差分はなんで出てるんだ？？
main をpullしたら直るやーつ？？

2023-05-04 03:56 UTC, yuzuki-aritomo commented on app/controllers/category_controller.rb
> +    params.permit(:name, :workspace_id)
`workspaceId`に変更してほしい！

2023-05-04 03:58 UTC, yuzuki-aritomo commented on app/models/category.rb
> +  end
これはちょっとややこしくて、rubyでは スネークケースが推奨なのでコードはスネークケースで書く。
一方 apiでjsonで返す時はキャメルケースで扱いたいというあれがあって、、
「apiから受け取り」と「apiに返却」の時はキャメルケース変換をするという処理を書いています、、

2023-05-04 05:28 UTC, liverHawk commented on app/controllers/category_controller.rb
> +                                  })
あー、なるほど。確認します。

2023-05-06 04:53 UTC, yamato-1205 approved these changes
👍

2023-05-08 01:04 UTC, yuzuki-aritomo requested changes
一つだけ！

2023-05-08 01:04 UTC, yuzuki-aritomo commented on app/controllers/category_controller.rb
> +  end
同一 `workspace`に複数userが存在した場合うまく動かないと思う！
find_byは最初にヒットしたuserを取得するので別userを取得する可能性がある！

2023-05-08 06:47 UTC, yuzuki-aritomo requested changes
このPRでのコメントで書くとずれるかもなんだけど、中間テーブルがうまく設定出来てなさそうなので
以下のように変更すると `current_user.workspaces`で取得できます!

```
# 中間テーブル
has_many :workspace_users, dependent: :destroy #この一文を先に書く！
has_many :workspaces, through: :workspace_users
```

2023-05-08 06:47 UTC, yuzuki-aritomo commented on app/controllers/category_controller.rb
> +    params = create_params
別のapiでも使用したくなると思うので `workspace_id`を引数にして定義したい！

2023-05-08 06:47 UTC, yuzuki-aritomo commented on app/controllers/category_controller.rb
> +    end
`!current_user.workspaces.exists?(id: workspace_id)`
こんな感じで書くときれいにかけると思う！

2023-05-08 06:47 UTC, yuzuki-aritomo requested changes
このPRでのコメントで書くとずれるかもなんだけど、中間テーブルがうまく設定出来てなさそうなので
以下のように変更すると `current_user.workspaces`で取得できます!

```
# 中間テーブル
has_many :workspace_users, dependent: :destroy #この一文を先に書く！
has_many :workspaces, through: :workspace_users
```

2023-05-09 04:18 UTC, liverHawk commented on app/controllers/category_controller.rb
> +    end
エラー出ました。
***Cannot have a has_many :through association 'User#workspaces' which goes through 'User#workspace_users' before the through association is defined.***

2023-05-09 12:52 UTC, yuzuki-aritomo approved these changes
![LGTM](https://media.giphy.com/media/xUPGcCn9z52cVjShm8/source.gif)

2023-05-09 12:59 UTC, merged