roomのgetの実装
CodeGateCircle/communication_app_back pull request #21
Opened 2023-05-07 14:01 UTC by yamato-1205

branch名とやってることが違うことに今気づきました
今回はユーザーが指定したworkspaceでユーザーが所属しているroom一覧をカテゴリで分けて出力しています

2023-05-08 00:50 UTC, yuzuki-aritomo requested changes

2023-05-08 00:50 UTC, yuzuki-aritomo commented on app/controllers/rooms_controller.rb
> +      end
N+1になってるので修正してほしい！
一度のsqlで書けないかな、、
`workspace.find(workspace_id).rooms.where(user_id: current_user.id)`的な感じで

2023-05-08 00:50 UTC, yuzuki-aritomo commented on app/controllers/rooms_controller.rb
> +  end
共通化したいから `user_model` か `application_controller` に書いてもいいかも

2023-05-08 00:50 UTC, yuzuki-aritomo commented on config/routes.rb
> +  get '/rooms', to: 'rooms#show'
一覧取得は関数名を `index`にしたいかも。`show`は個別表示のイメージが強い、

2023-05-09 04:55 UTC, yamato-1205 commented on app/controllers/rooms_controller.rb
> +        rooms[i].store('rooms', Room.where(id: current_user.rooms).where(category_id: category['id']).where(is_deleted: false).select(:id, :name).map(&:room_show_format_res))
N+1問題はこういうことであってます？

2023-05-09 05:05 UTC, yamato-1205 commented on app/controllers/rooms_controller.rb
> +        rooms[i].store('rooms', Room.where(id: current_user.rooms).where(category_id: category['id']).where(is_deleted: false).select(:id, :name).map(&:room_show_format_res))
これまだN＋1解消されてないですね
かんがえます

2023-05-10 12:50 UTC, yuzuki-aritomo approved these changes
![LGTM](https://user-images.githubusercontent.com/732828/30897015-ee5c02ec-a38e-11e7-8a96-3bc3708bab11.png)

2023-05-10 13:17 UTC, merged