edit(update) profile について
CodeGateCircle/communication_app_back pull request #26
Opened 2023-05-13 07:03 UTC by liverHawk

ルート、関数を定義→テストコード、という形で書きました。

2023-05-14 13:05 UTC, yuzuki-aritomo approved these changes
OK!
open apiの追加だけお願い！

2023-05-15 04:58 UTC, liverHawk commented
openapiについては追加したので、マージしても大丈夫ですか？？

2023-05-15 06:18 UTC, yuzuki-aritomo requested changes
レビュー漏れてしまってて気づいた部分をコメントした！
後からコメントでごめん:pray:

2023-05-15 06:18 UTC, yuzuki-aritomo commented on config/routes.rb
> +  put '/profile/edit', to: 'profile#edit'
method が `put`ならエンドポイントにeditは付ける必要がなくて`PUT /profile`でいいと思う

2023-05-15 06:18 UTC, yuzuki-aritomo commented on docs/openapi.yml
> +    user_data:
キャメルケースで統一しているのでキャメルケースでお願いします

2023-05-15 06:18 UTC, yuzuki-aritomo commented on spec/requests/profile_spec.rb
> +      expect(res['data']['image']).to eq(@user.image)
期待する出力は `request body`に含まれる値なので `body[:name]`をチェックしてほしい！

2023-05-15 06:18 UTC, yuzuki-aritomo requested changes
レビュー漏れてしまってて気づいた部分をコメントした！
後からコメントでごめん:pray:

2023-05-15 06:53 UTC, liverHawk commented
テストコードも通って修正完了です。

2023-05-15 07:26 UTC, yuzuki-aritomo approved these changes
![LGTM](https://media.giphy.com/media/OF4PIvoHuO2ze/giphy.gif)

2023-05-15 07:27 UTC, merged