Category serializer
CodeGateCircle/communication_app_back pull request #30
Opened 2023-05-17 01:48 UTC by liverHawk

categoryControllerのbefore actionにキャメルケースへの変更の定義を追加。
serializerは作り、renderには明記しなくても大丈夫とのことだったので書いてません。
テストコードはそのままです。

2023-05-17 01:54 UTC, liverHawk reviewed
POST /categoriesはテスト通りました

2023-05-17 01:54 UTC, liverHawk commented on app/controllers/application_controller.rb
> +  # end
最初のシリアライザーが良ければ、残りのものとこのコメントアウトも訂正します

2023-05-18 00:29 UTC, yamato-1205 commented on app/controllers/application_controller.rb
> +  # end
いいんじゃないかな？

2023-05-18 01:58 UTC, yamato-1205 commented on app/controllers/category_controller.rb
> +  before_action :authenticate_user!, :snake_to_camel_params
ApplicationControllerでbefore_action :snake_to_camel_params書いてるからここでわざわざ書かなくてもいいと思う！

2023-05-18 05:29 UTC, yuzuki-aritomo requested changes
コードはOK!!
open apiの変更もお願い！

2023-05-18 05:29 UTC, yuzuki-aritomo commented on app/serializers/category_serializer.rb
> +  # rails g serializer [model name]
細かいけどこのコメントは必要なさそうなので削除して貰えると！

2023-05-18 05:29 UTC, yuzuki-aritomo requested changes
コードはOK!!
open apiの変更もお願い！

2023-05-18 14:47 UTC, yamato-1205 approved these changes
👍

2023-05-19 02:18 UTC, yuzuki-aritomo approved these changes
![LGTM](https://media.giphy.com/media/xUA7b0UcdO2c8BGAec/giphy.gif)

2023-05-19 05:17 UTC, merged