Serializer
CodeGateCircle/communication_app_back pull request #31
Opened 2023-05-19 08:13 UTC by liverHawk

出力データの直列化

2023-05-19 08:28 UTC, liverHawk reviewed
修正点もあるが、ほとんどファイナル。
大幅変更がroom関係あります。

2023-05-19 08:28 UTC, liverHawk commented on app/controllers/rooms_controller.rb
> +      categories = Category.where(workspace_id: params[:workspace_id]).order(id: :desc)
推奨ということで。

2023-05-19 08:28 UTC, liverHawk commented on app/controllers/workspaces_controller.rb
> -  def create_params_id
create_params_idの削除

2023-05-19 08:28 UTC, liverHawk commented on app/serializers/category_serializer.rb
> +  has_many :rooms, if: -> { object[:rooms].present? && p(object) }, serializer: RoomSerializer
p の削除

2023-05-19 08:28 UTC, liverHawk commented on app/serializers/room_serializer.rb
roomのシリアライザーの設定。
属性によってある時ないときあるのでifの追加。

2023-05-19 08:28 UTC, liverHawk commented on spec/requests/room_spec.rb
> +        expect(res.size).to eq(categories.length)
**重要**

属性がなくなりました。

2023-05-19 08:28 UTC, liverHawk commented on spec/requests/room_spec.rb
ワークスペース、rooms、ルームの順に引数が並んでます。

2023-05-19 08:28 UTC, liverHawk commented on spec/requests/workspace_spec.rb
data属性の削除

2023-05-20 04:46 UTC, liverHawk reviewed
修正とopenapiの編集

2023-05-20 04:46 UTC, liverHawk commented on app/controllers/category_controller.rb
workspaceに属しているかの判定を継承メソッドに変更。
また、条件分岐はreturnを使って途中で抜けれるようにした。

2023-05-20 04:46 UTC, liverHawk commented on docs/openapi.yml
> +        room:
roomなので。

2023-05-21 03:37 UTC, yuzuki-aritomo requested changes
2つだけ気になった！
それ以外は良さそう！

2023-05-21 03:37 UTC, yuzuki-aritomo commented on app/controllers/category_controller.rb
> +    belong_to_workspace?(params[:workspace_id])
`params[:workspace_id]`に入れてる理由ってあったりする？？
特に理由がなければ`workspace_id`とかの変数名の方がいいと思う！

2023-05-21 03:37 UTC, yuzuki-aritomo commented on app/serializers/room_serializer.rb
> +  attribute :workspace_id, if: -> { object.workspace_id.present? }
[memo]
`null: false`の設定をし忘れてるのか、、原理的にはworkspaceは必ず存在するけど一旦はこれでOK！

2023-05-21 03:37 UTC, yuzuki-aritomo requested changes
2つだけ気になった！
それ以外は良さそう！

2023-05-23 07:42 UTC, yamato-1205 commented on app/controllers/rooms_controller.rb
> +      categories = Category.where(workspace_id: params[:workspace_id]).order(id: :desc)
知らなかった〜

2023-05-23 07:51 UTC, yamato-1205 commented on app/controllers/category_controller.rb
> +    belong_to_workspace?(params[:workspace_id])
@yuzuki-aritomo 
自分もあんまりわかってないですがこれってbelong_to_workspace?の関数を実行する前に
`workspace_id = params[:workspace_id]`
みたいに新たな変数用意してその変数を関数に渡したほうがいいってことですか？

2023-05-23 07:55 UTC, yamato-1205 approved these changes

2023-05-23 12:11 UTC, yuzuki-aritomo approved these changes
![LGTM](https://media.giphy.com/media/H7ZO0pGybYely/giphy.gif)

2023-05-23 12:11 UTC, merged