Workspaceのinvite定義
CodeGateCircle/communication_app_back pull request #33
Opened 2023-05-27 06:57 UTC by liverHawk

ルートの定義

ユーザーがいるかどうかの確認後、ワークスペースに追加する。
すでにいるときはエラーを出す。

テストコードの実装。

2023-05-27 07:14 UTC, liverHawk reviewed
とりあえず、くそ簡単な感じで。

2023-05-27 07:14 UTC, liverHawk commented on app/controllers/workspaces_controller.rb
> +    workspace_user = WorkspaceUser.new({
id, emailが登録と違う場合はエラー。
この二つは追加する人の情報。

2023-05-27 07:14 UTC, liverHawk commented on app/controllers/workspaces_controller.rb
# 実装の方向性(招待方法)

- 未登録のユーザーはemailで
- 登録済みであればidだけでいきたいところではあるが、間違っている可能性を考えるとちょっと不安ではある
  - 未登録なら、id=0にしたり、負の数にすることで条件分岐すればいいかと。

# 現在

idとメールで情報を確認して追加。

2023-05-28 06:25 UTC, yuzuki-aritomo requested changes
workspaceにemailで招待したときに、userが存在しない場合はエラーで返したいかも。
`そのemailアドレスのユーザーはいません`的な

2023-05-28 06:25 UTC, yuzuki-aritomo commented on app/controllers/workspaces_controller.rb
> +    workspace_user = WorkspaceUser.new({
これってフロント側で`user_id`って取得出来る？？
たとえば `test@gamil.com`さんを招待したいときにその人の`user_id`ってどこから取得できたっけ？と思い

2023-05-28 06:25 UTC, yuzuki-aritomo commented on app/controllers/workspaces_controller.rb
> +
`workspace_id`で認証チェックしてほしい！
今だと他のworkspaceに招待できてしまうと思う

2023-05-28 08:53 UTC, liverHawk commented on app/controllers/workspaces_controller.rb
> +    workspace_user = WorkspaceUser.new({
IDとメールアドレスを同時にとれることはないからどっちかに絞る感じかなと。

単純に行くならID。

2023-05-28 08:54 UTC, liverHawk commented on app/controllers/workspaces_controller.rb
> +
テストしてみますわ。

2023-05-29 06:57 UTC, yamato-1205 commented on app/controllers/workspaces_controller.rb
> +    unless WorkspaceUser.find_by(user_id: params[:user_id], workspace_id: params[:workspace_id])
application_controllerにユーザーがワークスペースに所属してるかどうか調べる関数あるからそれ使えば良さそう？
あとuser_idはcurrent_user.idで取り出せるからわざわざフロントから受け取らなくてもいいかな

2023-05-30 10:11 UTC, yuzuki-aritomo commented on app/controllers/workspaces_controller.rb
> +    workspace_user = WorkspaceUser.new({
所属しているワークスペースに ユーザーAを招待したいってなったときにユーザーAのuser_idを確認する方法が現状ないと思うからemailのみで招待するほうが自然な気がする。
emailだとユーザーもわかるからそのまま入力してもらうことが出来る

2023-05-30 14:05 UTC, liverHawk commented on app/controllers/workspaces_controller.rb
> +    workspace_user = WorkspaceUser.new({
その方向で変更しました。

2023-05-31 04:37 UTC, yuzuki-aritomo approved these changes
LGMT!!!
open api のコンフリクトだけ修正してもらえると！

2023-05-31 04:37 UTC, yuzuki-aritomo commented on db/migrate/20230530131434_set_unique_columns.rb
> +    add_index :workspace_users, [:workspace_id, :user_id], unique: true
👍🏻

2023-05-31 04:37 UTC, yuzuki-aritomo commented on spec/requests/workspace_spec.rb
> +    end
これは確認用コーデで消し忘れなやつ？

2023-05-31 04:37 UTC, yuzuki-aritomo approved these changes
LGMT!!!
open api のコンフリクトだけ修正してもらえると！

2023-05-31 04:37 UTC, yuzuki-aritomo approved these changes
LGMT!!!
open api のコンフリクトだけ修正してもらえると！

2023-05-31 07:32 UTC, liverHawk commented on spec/requests/workspace_spec.rb
> +    end
あえて残してるけど、消したほうがいいなら消す。

2023-06-02 01:54 UTC, merged