Api create reaction
CodeGateCircle/communication_app_back pull request #39
Opened 2023-06-27 11:39 UTC by yamato-1205

openapi未記入

2023-07-04 12:52 UTC, liverHawk commented on app/controllers/reaction_controller.rb
> +    render status: 200, json: reaction, serializer: ReactionSerializer
reactionが一つであれば、シリアライザーの記述はなくても自動で適応してくれます。

2023-07-04 12:54 UTC, liverHawk requested changes
一つだけ気になったところにコメントしてます。

2023-07-04 12:54 UTC, liverHawk commented on docs/openapi.yml
> +    reaction_data:
ここはキャメルケースの方がいいかと。reactionData

2023-07-04 13:16 UTC, yamato-1205 commented on docs/openapi.yml
> +    reaction_data:
これは確かに

2023-07-04 13:16 UTC, yamato-1205 commented on app/controllers/reaction_controller.rb
> +    render status: 200, json: reaction, serializer: ReactionSerializer
そうなんや！

2023-07-08 03:35 UTC, liverHawk approved these changes
# OK !

2023-07-16 07:22 UTC, yuzuki-aritomo approved these changes
OK!
細かいけど一点だけコメントしてる！（修正はしなくてもいいと思う！）

2023-07-16 07:22 UTC, yuzuki-aritomo commented on app/models/user.rb
> +  has_many :reaction
`has_many :reactions`の複数形の方が自然かな

2023-07-16 07:22 UTC, yuzuki-aritomo commented on app/models/message.rb
> +  has_many :reaction, dependent: :destroy
同じく！

2023-07-20 06:19 UTC, merged