preserve_imageで画像の保存が可能になった。返り値にはURLが返される
CodeGateCircle/communication_app_back pull request #53
Opened 2023-10-31 11:59 UTC by liverHawk

画像保存において、URLを返す

2023-10-31 12:00 UTC, liverHawk commented on app/controllers/application_controller.rb
> +  # 画像を保存する
ここが最も重要なところ。

2023-11-02 04:26 UTC, yuzuki-aritomo requested changes
`preserve_image`だけのAPIを作って欲しい！
responseとしてurlを返すAPI
んで`update`とかの時は request body に `image_url: url_string`を指定するようにしたいかな

なので profile imageをupdateする時は以下のようにしたい！
1. 画像upload api を叩いてurlを取得
2. 取得したurlを request bodyに含めて 更新 apiを叩く

2023-11-02 04:27 UTC, yuzuki-aritomo commented
それ以外は基本良さげ！！

2023-11-05 07:31 UTC, liverHawk commented
RailsのActive Storageだと、何かフィールドに紐づけて保存する必要があって、もし画像を保存するだけのAPIを作るには**別のデータベースが必要になる**のよ。それでもよければ実装するけど、、、

2023-11-05 07:34 UTC, liverHawk commented on app/controllers/profile_controller.rb
> -    user.user_image.attach(io:, filename: "#{current_user.name}_image")
ここみたいに、user_imageに紐づけてじゃないとできない。

2023-11-07 11:18 UTC, yuzuki-aritomo approved these changes
LGTM

2023-11-07 11:30 UTC, merged